logging:
  level:
    root: WARN
    org.springframework: WARN
    com.example: DEBUG
    org.apache.camel.component.mail: DEBUG

inboxConfig:
  host: myhost
  user: james
  outputEndpoint: vm:output
