logging:
  level:
    root: WARN
    org.springframework: WARN
    com.example: DEBUG
    org.apache.camel.component.mail: DEBUG

inboxConfig:
  host: myhost
  user: james
  sendEndpoint: smtp://${inboxConfig.user}@${inboxConfig.host}
  inputEndpoint: imap://${inboxConfig.user}@${inboxConfig.host}
  outputEndpoint: vm:output
